-- CREATE OR REPLACE TABLE `x-marketing.hyland.6sense_hive9_campaign_log` AS
TRUNCATE TABLE `x-marketing.hyland.6sense_hive9_campaign_log`;
INSERT INTO `x-marketing.hyland.6sense_hive9_campaign_log` 
(
  _end_date,
  _clicks,
  _ad_id,
  _status,
  _ad_group_id,
  _extract_date,
  _maximum_daily_spend,
  _ad_size,
  _account_vtr,
  _ecpm,
  _ecpc,
  _campaign_id,
  _spend,
  _start_date,
  _account_ctr,
  _accounts_reached,
  _date,
  _budget,
  _ad_group_name,
  _impressions,
  _ad_name,
  _ctr,
  _month_year,
  _segmentation,
  _campaign_name,
  _year,
  _execution_segment,
  _region,
  _hive9_id,
  _plan_area
)
SELECT DISTINCT
  _6sense._enddate AS _end_date,
  _6sense._clicks,
  _6sense._adid AS _ad_id,
  _6sense._status,
  _6sense._adgroupid AS _ad_group_id,
  _6sense._extractdate AS _extract_date,
  _6sense._maximumdailyspend AS _maximum_daily_spend,
  _6sense._adsize AS _ad_size,
  _6sense._accountvtr AS _account_vtr,
  _6sense._ecpm,
  _6sense._ecpc,
  _6sense._campaignid AS _campaign_id,
  _6sense._spend,
  _6sense._startdate AS _start_date,
  _6sense._accountctr AS _account_ctr,
  _6sense._accountsreached AS _accounts_reached,
  _6sense._date,
  _6sense._budget,
  _6sense._adgroupname AS _ad_group_name,
  _6sense._impressions,
  _6sense._adname AS _ad_name,
  _6sense._ctr,
  FORMAT_TIMESTAMP('%b %Y', PARSE_TIMESTAMP('%Y-%m-%d', _6sense._date)) AS _month_year,
  _hive9._segmentation,
  _hive9._campaignname AS _campaign_name,
  _hive9._year,
  _hive9._executionsegment AS _execution_segment,
  _hive9._region,
  _hive9._hive9id AS _hive9_id,
  _hive9._planarea AS _plan_area
FROM `x-marketing.hyland_mysql.db_6sense_daily_ad_performance` AS _6sense
LEFT JOIN `x-marketing.hyland_mysql.db_6sense_campaign_info_hive9` AS _hive9
  ON _6sense._campaignID = _hive9._campaignID