-- CREATE OR REPLACE TABLE `x-marketing.processunity.marketo_contacts_log` AS
TRUNCATE TABLE `x-marketing.processunity.marketo_contacts_log`;
INSERT INTO `x-marketing.processunity.marketo_contacts_log`
(
  _leadID, 
  _first_name,
  _last_name,
  _email,
  _account,
  _email_activity_count,
  _email_delivered_count,
  _email_opens_count,
  _email_CTA_click_count,
  _content_syndication_activity_count,
  _event_registered,
  _event_attended,
  _webinar_registration_count,
  _website_visit_count,
  _company_name,
  _job_title,
  _lead_score,
  _lead_nurture_entry,
  _lead_mql_qualified,
  _lead_mql_qualified_date,
  _wf_became_mql_date,
  _sal_qualified_date,
  _leads_sql_qualified_date,
  _lead_source,
  _wf_became_sql_date,
  _wf_became_sal_date
)
SELECT DISTINCT
  id AS _leadID,
  firstname AS _first_name,
  lastname AS _last_name,
  email AS _email,
  account__c AS _account,
  emailactivitycount AS _email_activity_count,
  emaildeliveredcount AS _email_delivered_count,
  emailopenscount AS _email_opens_count,
  emailctaclickcount AS _email_CTA_click_count,
  contentsyndicationactivitycount AS _content_syndication_activity_count,
  eventregistered AS _event_registered,
  eventattended AS _event_attended,
  webinarregistrationcount AS _webinar_registration_count,
  websitevisitscount AS _website_visit_count,
  company AS _company_name,
  title AS _job_title,
  leadscore AS _lead_score,
  leadnurtureentry AS _lead_nurture_entry,
  leadmqlqualified AS _lead_mql_qualified,
  leadmqlqualifieddate AS _lead_mql_qualified_date,
  wf_became_mql_date__c AS _wf_became_mql_date,
  salqualifieddate AS _sal_qualified_date,
  leadsqlqualifieddate AS _leads_sql_qualified_date,
  leadsource AS _lead_source,
  wf_became_sql_date__c AS _wf_became_sql_date,
  wf_became_sal_date__c AS _wf_became_sal_date
FROM `x-marketing.processunity_marketo.leads` 