--------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------ Sent to Sales Reporting Script ------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------


CREATE OR REPLACE TABLE `logicsource.sent_to_sales_mql` AS 
WITH 
#Query to pull the leads from salesforce_leads table generated by another script (spirion_salesforce_sf_leads)
leads_contacts AS (
  SELECT
    id AS _leadid,
    createddate AS _leadcreated,
    convertedcontactid AS _convertedcontactid,
    firstname AS _firstname,
    lastname AS _lastname,
    title AS _title,
    email AS _email,
    RIGHT(email, LENGTH(email) - STRPOS(email, '@')) AS _domain,
    convertedaccountid AS _convertedaccountid,
    company AS _accountname,
    industry AS _industry,
    country AS _country,
    -- member_type AS _member_type,
    status AS _lead_status,
     createddate AS _mql_date,
  lastmodifieddate AS _last_mql_date,
  createddate AS _sql_date,
    leadsource AS _leadsource,
    -- most_recent_lead_source__c AS _most_recent_lead_source__c,
    isconverted AS _isconverted_to_contact,
    -- memberJoinDate AS _memberJoinDate,
    CAST(NULL AS INTEGER) AS _tier,
    CAST(NULL AS INTEGER) AS _target_account,
   createddate AS _sent_date,
    EXTRACT(WEEK FROM createddate) AS _week, 
    EXTRACT(YEAR FROM createddate) AS _year,
    ROW_NUMBER() OVER(PARTITION BY email ORDER BY createddate DESC) AS rownum
  FROM 
    `logicsource_salesforce.Lead`
  /* LEFT JOIN
    (SELECT DISTINCT id AS accountid, industry, FROM `logicsource_salesforce.Account`) USING(accountid) */
  WHERE
    isdeleted = false
    AND status NOT IN ('Qualified')
), /* 
#Query to get the bombora report data - topics and average score
bTopics AS (
  SELECT 
    DISTINCT _domain, 
    EXTRACT(WEEK FROM _date)-1 AS _week, 
    EXTRACT(YEAR FROM _date) AS _year, 
    STRING_AGG(CONCAT(_topicname), ",\n" ORDER BY _topicname) AS _topics,
    ROUND(AVG(CAST(_compositescore AS INT64)),0) AS _weekly_avgCompositeScore, 
  FROM 
    logicsource.bombora_surge_report
  GROUP BY 
    1, 2, 3 
  ORDER BY 
    1, 2 DESC
), */ 
contact_engagement AS (
  SELECT
    DISTINCT _domain, 
    _email,
    _week, 
    _year,
    CONCAT("Opened: ", _emailOpens, "\n", "Clicked: ", _emailClicks, "\n", "Form Fills:", _gatedForms, "\n") AS _contact_engagements
  FROM
  (
    SELECT 
      DISTINCT
      _domain,
      _email,
      _date AS _timestamp,
      EXTRACT(WEEK FROM _date) AS _week,
      EXTRACT(YEAR FROM _date) AS _year,
      SUM(IF(_engagement = 'Email Opened', 1, 0)) AS _emailOpens,
      SUM(IF(_engagement = 'Email Clicked', 1, 0)) AS _emailClicks,
      SUM(IF(_engagement = 'Form Filled', 1, 0)) AS _gatedForms,
    FROM
      `logicsource.db_consolidated_engagements_log`
    WHERE
      _engagement IN ('Email Opened', 'Email Clicked', 'Form Filled')
    GROUP BY
      1, 2, 3
  )
),
first_party_score AS (
  SELECT 
    DISTINCT _domain, 
    _extract_date,
    EXTRACT(WEEK FROM _extract_date) - 1 AS _week, -- Minus 1 as the score is referring to the week before.
    EXTRACT(YEAR FROM _extract_date) AS _year,
     (COALESCE(_quarterly_email_score, 0) + COALESCE(_quarterly_content_synd_score , 0)+ COALESCE(_quarterly_organic_social_score , 0)+ COALESCE(_quarterly_form_fill_score , 0)+ COALESCE(_quarterly_paid_ads_score , 0)+ COALESCE(_quarterly_web_score, 0)+ COALESCE(_quarterly_organic_social_score, 0)) AS _t90_days_score
  FROM
    `logicsource.account_90days_score`
  ORDER BY
    _extract_date DESC
)
SELECT 
  DISTINCT leads_contacts.*EXCEPT(rownum),
  contact_engagement.*EXCEPT(_domain, _email, _week, _year),
  CAST(NULL AS STRING) AS _topics,
  CAST(NULL AS INTEGER) AS _weekly_avgCompositeScore,
  COALESCE(_t90_days_score, 0) AS _t90days_first_party_score,
  -- Intent is temp removed, to be added on in the future. Replacing with engagement score.
  -- CAST(NULL AS STRING) AS _intent
  IF(_t90_days_score > 14, 'High', 
        IF(_t90_days_score BETWEEN 1 AND 14, 'Low', 
          'No') ) AS _t90days_intent,
FROM 
  leads_contacts 
LEFT JOIN
  contact_engagement USING(_domain, _email, _week, _year)
/* LEFT JOIN 
  bTopics USING(_domain, _week, _year) */
LEFT JOIN 
  first_party_score USING(_domain, _week, _year)
WHERE 
  EXTRACT(YEAR FROM _leadcreated) IN (2022, 2023)
  AND  rownum = 1
;




