TRUNCATE TABLE `x-marketing.corcentric.salesforce_lead_contact`;
INSERT INTO `x-marketing.corcentric.salesforce_lead_contact` (
    label,	
    qualified_date,	
    _id,	
    contact_name,	
    email,	
    country,	
    mailingcity,	
    company,	
    accountid,	
    convertedaccountid,	
    lastmodifiedbyid,	
    convertedopportunityid,	
    casesafeid__c,	
    website,	
    convertedcontactid,	
    converted_lead_id__c,	
    converted,	
    lead_source_original__c,	
    state__c,	
    street,	
    createddate,	
    person_source__c,	
    person_source_sub_type__c,	
    outreachstage__c,	
    territory__c,	
    ownerid,	
    status,	
    leadsource,	
    business_needs__c,	
    leadsourcesubtypevalid__c,	
    ds_06c_last_evaluation__c,	
    ds_02_engaged__c,	
    ds_03_last_mql__c,	
    ds_06e_last_detailed_pricing__c,	
    ds_06d_last_negotiation__c,	
    ds_13_last_closed_no_decision__c,	
    ds_05_first_sql__c,	
    ds_09_last_closed_lost__c,	
    ds_06g_last_awaiting_signature__c,	
    ds_06d_last_evaluation__c,	
    ds_10_first_recycled__c,	
    ds_04_first_sal__c,	
    ds_05_last_sql__c,	
    ds_06e_first_detailed_pricing__c,	
    ds_13_first_closed_no_decision__c,	
    ds_06b_first_discovery__c,	
    ds_06a_last_qualification__c,	
    ds_08_fulfillment__c,	
    ds_04_last_working__c,	
    ds_06d_first_evaluation__c,	
    ds_12_trash__c,	
    ds_06b_last_discovery__c,	
    ds_06d_first_negotiation__c,	
    ds_06a_first_qualification__c,	
    ds_10_last_nurture__c,	
    ds_10_last_recycled__c,	
    ds_06g_first_awaiting_signature__c,	
    ds_06c_first_evaluation__c,	
    ds_06c_last_presentation__c,	
    ds_04_last_sal__c,	
    ds_01_known__c,	
    ds_04_first_working__c,	
    ds_06c_first_presentation__c,	
    ds_07_closed_won__c,	
    ds_09_first_closed_lost__c,	
    ds_06f_first_pricing_agreed__c,	
    ds_10_first_nurture__c,	
    ds_11_unqualified__c,	
    ds_03_first_mql__c,	
    ds_03_first_qp__c,	
    ds_06_last_sal__c,	
    ds_04_first_discovery__c,	
    ds_04_last_discovery__c,	
    ds_07_last_sql__c,	
    ds_05_last_mql__c,	
    ds_03_last_qp__c,	
    ds_06_first_sal__c,	
    ds_05_first_mql__c,	
    ds_07_first_sql__c,	
    ds_08_closed_won__c,	
    ds_08_first_opportunity__c,	
    ds_08_last_opportunity__c,	
    ds_days_in_mql__c
)
WITH contact AS (
    SELECT  
        'Contact' AS label,
        ds_03_last_mql__c AS qualified_date,
        id AS _id,
        name AS contact_name,
        email,
        mailingcountry AS country,
        mailingcity, 
        '' AS company,
        accountid,
        '' AS convertedaccountid, 
        lastmodifiedbyid, 
        '' AS convertedopportunityid, 
        casesafeid__c, 
        '' AS website, 
        '' AS convertedcontactid,
        converted_lead_id__c,
        IF(converted_lead_id__c IS NOT NULL, TRUE, FALSE) AS converted, 
        lead_source_original__c, 
        state__c, 
        '' AS street, 
        createddate, 
        person_source__c, 
        person_source_sub_type__c, 
        outreachstage__c, 
        territory__c,
        ownerid,
        status__c AS  status,
        leadsource, 
        business_needs__c, 
        CAST(NULL AS BOOL) AS leadsourcesubtypevalid__c,
        ds_06c_last_evaluation__c, 
        ds_02_engaged__c, 
        ds_03_last_mql__c, 
        ds_06e_last_detailed_pricing__c, 
        ds_06d_last_negotiation__c, 
        ds_13_last_closed_no_decision__c, 
        ds_05_first_sql__c, 
        ds_09_last_closed_lost__c, 
        ds_06g_last_awaiting_signature__c, 
        ds_06d_last_evaluation__c, 
        ds_10_first_recycled__c, 
        ds_04_first_sal__c, 
        ds_05_last_sql__c, 
        ds_06e_first_detailed_pricing__c, 
        ds_13_first_closed_no_decision__c, 
        ds_06b_first_discovery__c, 
        ds_06a_last_qualification__c, 
        ds_08_fulfillment__c, 
        ds_04_last_working__c, 
        ds_06d_first_evaluation__c, 
        ds_12_trash__c, 
        ds_06b_last_discovery__c, 
        ds_06d_first_negotiation__c, 
        ds_06a_first_qualification__c, 
        ds_10_last_nurture__c, 
        ds_10_last_recycled__c, 
        ds_06g_first_awaiting_signature__c, 
        ds_06c_first_evaluation__c, 
        ds_06c_last_presentation__c, 
        ds_04_last_sal__c, 
        ds_01_known__c, 
        ds_04_first_working__c, 
        ds_06c_first_presentation__c, 
        ds_07_closed_won__c, 
        ds_09_first_closed_lost__c, 
        ds_06f_first_pricing_agreed__c, 
        ds_10_first_nurture__c, 
        ds_11_unqualified__c, 
        ds_03_first_mql__c, 
        ds_03_first_qp__c, 
        ds_06_last_sal__c, 
        ds_04_first_discovery__c, 
        ds_04_last_discovery__c, 
        ds_07_last_sql__c, 
        ds_05_last_mql__c, 
        ds_03_last_qp__c, 
        ds_06_first_sal__c, 
        ds_05_first_mql__c, 
        ds_07_first_sql__c, 
        ds_08_closed_won__c, 
        ds_08_first_opportunity__c, 
        ds_08_last_opportunity__c, 
        NULL AS ds_days_in_mql__c 
    FROM `x-marketing.corcentric_salesforce.Contact`
    WHERE isdeleted IS FALSE
), 
leads AS (
    SELECT  
        'Lead' AS label,
        ds_03_last_mql__c AS qualified_date,
        id AS contact_id,
        name AS contact_name,
        email,
        country AS country,
        city, 
        company,
        '' AS accountid,
        convertedaccountid,  
        lastmodifiedbyid, 
        convertedopportunityid, 
        casesafeid__c, 
        website, 
        convertedcontactid,
        '' AS converted_lead_id__c,
        IF(convertedcontactid IS NOT NULL, TRUE, FALSE) AS converted,
        lead_source_original__c, 
        state__c, 
        street, 
        createddate, 
        person_source__c, 
        person_source_sub_type__c, 
        outreachstage__c, 
        territory__c,
        ownerid,
        status AS status,
        leadsource, 
        business_needs__c, 
        leadsourcesubtypevalid__c,
        CAST(NULL AS TIMESTAMP) ds_06c_last_evaluation__c, 
        ds_02_engaged__c, 
        ds_03_last_mql__c, 
        CAST(NULL AS TIMESTAMP) ds_06e_last_detailed_pricing__c, 
        CAST(NULL AS TIMESTAMP) ds_06d_last_negotiation__c, 
        CAST(NULL AS TIMESTAMP) ds_13_last_closed_no_decision__c, 
        ds_05_first_sql__c, 
        CAST(NULL AS TIMESTAMP) ds_09_last_closed_lost__c, 
        CAST(NULL AS TIMESTAMP) ds_06g_last_awaiting_signature__c, 
        CAST(NULL AS TIMESTAMP) ds_06d_last_evaluation__c, 
        ds_10_first_recycled__c, 
        ds_04_first_sal__c, 
        ds_05_last_sql__c, 
        CAST(NULL AS TIMESTAMP) ds_06e_first_detailed_pricing__c, 
        CAST(NULL AS TIMESTAMP) ds_13_first_closed_no_decision__c, 
        CAST(NULL AS TIMESTAMP) ds_06b_first_discovery__c, 
        CAST(NULL AS TIMESTAMP) ds_06a_last_qualification__c, 
        CAST(NULL AS TIMESTAMP) ds_08_fulfillment__c, 
        ds_04_last_working__c, 
        CAST(NULL AS TIMESTAMP) ds_06d_first_evaluation__c, 
        ds_12_trash__c, 
        CAST(NULL AS TIMESTAMP) ds_06b_last_discovery__c, 
        CAST(NULL AS TIMESTAMP) ds_06d_first_negotiation__c, 
        CAST(NULL AS TIMESTAMP) ds_06a_first_qualification__c, 
        ds_10_last_nurture__c, 
        ds_10_last_recycled__c, 
        CAST(NULL AS TIMESTAMP) ds_06g_first_awaiting_signature__c, 
        CAST(NULL AS TIMESTAMP) ds_06c_first_evaluation__c, 
        CAST(NULL AS TIMESTAMP) ds_06c_last_presentation__c, 
        ds_04_last_sal__c, 
        ds_01_known__c, 
        ds_04_first_working__c, 
        CAST(NULL AS TIMESTAMP) ds_06c_first_presentation__c, 
        CAST(NULL AS TIMESTAMP) ds_07_closed_won__c, 
        CAST(NULL AS TIMESTAMP) ds_09_first_closed_lost__c, 
        CAST(NULL AS TIMESTAMP) ds_06f_first_pricing_agreed__c, 
        ds_10_first_nurture__c, 
        ds_11_unqualified__c, 
        ds_03_first_mql__c, 
        ds_03_first_qp__c, 
        ds_06_last_sal__c, 
        ds_04_first_discovery__c, 
        ds_04_last_discovery__c, 
        ds_07_last_sql__c, 
        ds_05_last_mql__c, 
        ds_03_last_qp__c, 
        ds_06_first_sal__c, 
        ds_05_first_mql__c, 
        ds_07_first_sql__c, 
        CAST(NULL AS TIMESTAMP) ds_08_closed_won__c, 
        CAST(NULL AS TIMESTAMP) ds_08_first_opportunity__c, 
        CAST(NULL AS TIMESTAMP) ds_08_last_opportunity__c,
        ds_days_in_mql__c 
    FROM `x-marketing.corcentric_salesforce.Lead`
    WHERE isdeleted IS FALSE
) 
SELECT 
    * 
FROM contact
UNION ALL 
SELECT 
    * 
FROM leads;